import type {
  ProductEngineeringContent,
  SolutionArea,
  SolutionDetailContent,
  SolutionAssembly,
  SolutionAudience,
  SolutionId,
  SolutionProcessStep,
  SpecialistCard,
} from "./models"

export const solutionAreas: SolutionArea[] = [
  {
    id: "product-engineering",
    number: "01",
    total: "06",
    title: "Product Engineering",
    discipline: "Digital products and systems built for impact.",
    description:
      "Digital products, enterprise platforms, mobile applications and integrated systems built for real operations.",
    href: "/solutions/product-engineering",
    accent: "green",
    icon: "box",
  },
  {
    id: "cloud-infrastructure",
    number: "02",
    total: "06",
    title: "Cloud & Infrastructure",
    discipline: "Architecture, deployment and reliable operations.",
    description:
      "Architecture, deployment, infrastructure modernization and reliable, scalable operations in the cloud and on-premise.",
    href: "/solutions/cloud-infrastructure",
    accent: "green",
    icon: "cloud",
  },
  {
    id: "ai-data",
    number: "03",
    total: "06",
    title: "AI & Data",
    discipline: "Data platforms, analytics and intelligence.",
    description:
      "Data platforms, analytics, machine learning, intelligent automation and applied AI that drive better outcomes.",
    href: "/solutions/ai-data",
    accent: "violet",
    icon: "orbit",
  },
  {
    id: "cybersecurity",
    number: "04",
    total: "06",
    title: "Cybersecurity",
    discipline: "Security built into every layer.",
    description:
      "Secure architecture, application security, infrastructure protection, identity and continuous monitoring.",
    href: "/solutions/cybersecurity",
    accent: "blue",
    icon: "shield",
  },
  {
    id: "experience-design",
    number: "05",
    total: "06",
    title: "Experience & Design",
    discipline: "Product strategy, UX and design systems.",
    description:
      "Product strategy, user experience, interfaces, design systems and digital experiences that delight and perform.",
    href: "/solutions/experience-design",
    accent: "coral",
    icon: "sun",
  },
  {
    id: "venture-building",
    number: "06",
    total: "06",
    title: "Venture Building",
    discipline: "From opportunity to operating company.",
    description:
      "From opportunity validation through product creation, launch and scale for new technology ventures.",
    href: "/solutions/venture-building",
    accent: "gold",
    icon: "landmark",
  },
]

export const solutionAreaById = Object.fromEntries(
  solutionAreas.map((area) => [area.id, area]),
) as Record<SolutionId, SolutionArea>

export const solutionAssemblies: SolutionAssembly[] = [
  {
    id: "digital-lending-platform",
    title: "Build a digital lending platform",
    description: "Integrated solution that powers lending operations end-to-end.",
    areas: ["product-engineering", "experience-design", "cloud-infrastructure", "cybersecurity", "ai-data"],
    icon: "users",
  },
  {
    id: "operational-system",
    title: "Modernize an operational system",
    description: "Modern systems that are secure, scalable and data-driven.",
    areas: ["product-engineering", "cloud-infrastructure", "ai-data", "cybersecurity"],
    icon: "building",
  },
  {
    id: "intelligent-product",
    title: "Build an intelligent product",
    description: "Intelligence, experience and scale built into the product.",
    areas: ["product-engineering", "ai-data", "experience-design", "cloud-infrastructure"],
    icon: "rocket",
  },
]

export const solutionProcess: SolutionProcessStep[] = [
  {
    id: "understand",
    number: "01",
    title: "Understand",
    description: "We listen, research and clarify the real problem, objectives and constraints.",
    icon: "search",
  },
  {
    id: "assemble",
    number: "02",
    title: "Assemble",
    description: "We assemble the right ANTIKRA companies and capabilities for impact.",
    icon: "layout",
  },
  {
    id: "architect",
    number: "03",
    title: "Architect",
    description: "We design the solution architecture, roadmap and delivery approach.",
    icon: "pencil",
  },
  {
    id: "build",
    number: "04",
    title: "Build",
    description: "We engineer, integrate and test the solution with transparency and rigor.",
    icon: "code",
  },
  {
    id: "operate",
    number: "05",
    title: "Operate",
    description: "We deploy, monitor and operate for reliability, performance and security.",
    icon: "cloudUpload",
  },
  {
    id: "evolve",
    number: "06",
    title: "Evolve",
    description: "We iterate, optimize and scale as your needs and the market evolve.",
    icon: "growth",
  },
]

export const solutionAudiences: SolutionAudience[] = [
  {
    id: "financial-services",
    title: "Financial Services",
    description: "Banks, MFIs, fintechs and financial institutions modernizing products and operations.",
    icon: "landmark",
  },
  {
    id: "mobility",
    title: "Mobility &",
    description: "Automotive, transportation and mobility platforms powering connected services.",
    icon: "car",
  },
  {
    id: "enterprise",
    title: "Enterprise Operations",
    description: "Organizations optimizing processes, systems and operational performance.",
    icon: "briefcase",
  },
  {
    id: "public-sector",
    title: "Public Sector",
    description: "Government agencies and public institutions delivering better digital services.",
    icon: "landmark",
  },
  {
    id: "ventures",
    title: "Emerging Ventures",
    description: "Founders and organizations building new technology ventures and startups.",
    icon: "rocket",
  },
]

export const specialistCards: SpecialistCard[] = [
  {
    id: "mechanism",
    name: "Mechanism",
    discipline: "Product Engineering",
    description: "Builds robust, scalable and reliable products.",
    icon: "box",
    accent: "bronze",
  },
  {
    id: "cosmos",
    name: "Cosmos",
    discipline: "Infrastructure",
    description: "Delivers scalable and secure infrastructure.",
    icon: "cloud",
    accent: "green",
  },
  {
    id: "orrery",
    name: "Orrery",
    discipline: "Data & Intelligence",
    description: "Turns data into intelligence and insight.",
    icon: "orbit",
    accent: "violet",
  },
  {
    id: "astra",
    name: "Astra",
    discipline: "Security",
    description: "Protects systems, data and identities.",
    icon: "shield",
    accent: "blue",
  },
  {
    id: "helios",
    name: "Helios",
    discipline: "Experience & Design",
    description: "Designs experiences people love to use.",
    icon: "sun",
    accent: "coral",
  },
  {
    id: "olympia",
    name: "Olympia",
    discipline: "Venture Building",
    description: "Builds and scales new ventures.",
    icon: "venture",
    accent: "gold",
  },
]

export const productEngineeringContent: ProductEngineeringContent = {
  solution: solutionAreas[0],
  lead: "Build technology around the operation.",
  summary:
    "From new digital products to complex operational platforms, ANTIKRA designs and engineers systems around how organizations actually work.",
  capabilityLabel: "What we can build",
  capabilities: [
    {
      id: "enterprise-platforms",
      title: "Enterprise Platforms",
      description: "Operational systems that connect people, processes and data across the organization.",
      icon: "layout",
    },
    {
      id: "web-applications",
      title: "Web Applications",
      description: "Secure, scalable web applications for complex workflows and business processes.",
      icon: "globe",
    },
    {
      id: "mobile-applications",
      title: "Mobile Applications",
      description: "Field, workforce and customer-facing mobile apps that work online and offline.",
      icon: "phone",
    },
    {
      id: "digital-products",
      title: "Digital Products",
      description: "End-to-end development of commercial technology products from concept to scale.",
      icon: "box",
    },
    {
      id: "internal-systems",
      title: "Internal Systems",
      description: "Purpose-built software that replaces fragmented tools and manual processes.",
      icon: "settings",
    },
    {
      id: "integrations-apis",
      title: "Integrations & APIs",
      description: "Connect systems, services and data with secure, well-documented integrations.",
      icon: "link",
    },
  ],
  processLabel: "From operational problem to working system",
  process: [
    {
      id: "understand",
      number: "01",
      title: "Understand Operations",
      description: "We study your processes, challenges, data and goals to understand the real problem.",
      icon: "search",
    },
    {
      id: "model",
      number: "02",
      title: "Model Workflows",
      description: "We map how work happens and define requirements and business rules.",
      icon: "layout",
    },
    {
      id: "architect",
      number: "03",
      title: "Architect System",
      description: "We design the right architecture, data model and technology stack for your needs.",
      icon: "box",
    },
    {
      id: "design",
      number: "04",
      title: "Design Experience",
      description: "We craft intuitive interfaces and seamless experiences for your users.",
      icon: "pencil",
    },
    {
      id: "engineer",
      number: "05",
      title: "Engineer & Build",
      description: "We build with quality, security and performance using modern engineering practices.",
      icon: "code",
    },
    {
      id: "deploy",
      number: "06",
      title: "Deploy & Evolve",
      description: "We deploy to production and continuously evolve the system as your needs grow.",
      icon: "rocket",
    },
  ],
  architecture: specialistCards.slice(0, 5),
  work: [
    {
      id: "rembeh",
      title: "Rembeh",
      category: "Financial Operations Platform",
      description: "Full-stack platform for lending operations, collections and portfolio management.",
      visual: "rembeh",
      accent: "green",
    },
    {
      id: "carmie",
      title: "Carmie",
      category: "Automotive Services Platform",
      description: "Connecting vehicle owners with automotive service providers across Uganda.",
      visual: "carmie",
      accent: "blue",
    },
    {
      id: "enterprise",
      title: "Enterprise Solutions",
      category: "Operational Systems",
      description: "Custom operational systems and digital tools delivered for organizations across multiple sectors.",
      visual: "enterprise",
      accent: "green",
    },
  ],
  engagementModels: [
    {
      id: "new-product",
      title: "Build a New Product",
      description: "From idea validation and MVPs to full-scale product development and launch.",
      icon: "lightbulb",
    },
    {
      id: "modernize",
      title: "Modernize Systems",
      description: "Replace legacy or manual processes with modern, secure and scalable platforms.",
      icon: "refresh",
    },
    {
      id: "extend",
      title: "Extend Platforms",
      description: "Add new modules, integrations and capabilities to existing systems.",
      icon: "layout",
    },
    {
      id: "technical-partnership",
      title: "Technical Partnership",
      description: "Long-term engineering partnership to build, operate and evolve your technology.",
      icon: "users",
    },
  ],
  productionPrinciples: [
    {
      id: "architecture",
      title: "Architecture & Scalability",
      description: "Systems designed for growth and high performance.",
      icon: "layers",
    },
    {
      id: "security",
      title: "Security by Design",
      description: "Security built in from day one, not added later.",
      icon: "shield",
    },
    {
      id: "quality",
      title: "Testing & Quality",
      description: "Automated testing, code quality and reliability.",
      icon: "check",
    },
    {
      id: "observability",
      title: "Observability",
      description: "Monitoring, logging and insights in real time.",
      icon: "growth",
    },
    {
      id: "documentation",
      title: "Documentation",
      description: "Clear documentation for your team and the future.",
      icon: "book",
    },
    {
      id: "maintainability",
      title: "Maintainability",
      description: "Clean, modular code that is easy to maintain.",
      icon: "wrench",
    },
    {
      id: "deployment",
      title: "Deployment Strategy",
      description: "Reliable deployments with zero- or low-downtime.",
      icon: "cloudUpload",
    },
  ],
  next: solutionAreas[1],
}

export const solutionDetailPages: Record<string, SolutionDetailContent> = {
  "cloud-infrastructure": {
    id: "cloud-infrastructure",
    solution: solutionAreaById["cloud-infrastructure"],
    heading: "Cloud & Infrastructure",
    breadcrumb: "ANTIKRA / Solutions / Cloud & Infrastructure",
    heroIconAccent: "green",
    visual: "cloud",
    lead: "Infrastructure built for what comes next.",
    summary:
      "ANTIKRA designs, deploys and operates secure infrastructure that keeps digital systems available, observable and ready to scale.",
    primaryActionLabel: "Discuss your infrastructure",
    capabilityLabel: "What we can deliver",
    capabilities: [
      {
        id: "cloud-architecture",
        title: "Cloud Architecture",
        description: "Architecture designed around application, security and operational requirements.",
        icon: "cloud",
      },
      {
        id: "application-infrastructure",
        title: "Application Infrastructure",
        description: "Production environments for web, mobile, APIs and backend systems. Built for performance and scale.",
        icon: "server",
      },
      {
        id: "infrastructure-modernization",
        title: "Infrastructure Modernization",
        description: "Move fragmented or legacy infrastructure toward a modern, secure and maintainable architecture.",
        icon: "growth",
      },
      {
        id: "deployment-automation",
        title: "Deployment & Automation",
        description: "CI/CD pipelines, infrastructure automation and repeatable releases that reduce risk and speed delivery.",
        icon: "code",
      },
      {
        id: "reliability-observability",
        title: "Reliability & Observability",
        description: "Monitoring, logging, alerting and dashboards for full visibility into system health and performance.",
        icon: "eye",
      },
      {
        id: "backup-recovery",
        title: "Backup & Recovery",
        description: "Resilience, data protection and recovery planning to keep your business continuous.",
        icon: "refresh",
      },
    ],
    processLabel: "From application to reliable operation",
    process: [
      {
        id: "assess",
        number: "01",
        title: "Assess",
        description: "Understand your systems, workloads, risks and performance goals.",
        icon: "search",
      },
      {
        id: "architect",
        number: "02",
        title: "Architect",
        description: "Design the right infrastructure and operating model.",
        icon: "pencil",
      },
      {
        id: "provision",
        number: "03",
        title: "Provision",
        description: "Build environments using infrastructure as code and best practices.",
        icon: "box",
      },
      {
        id: "deploy",
        number: "04",
        title: "Deploy",
        description: "Release applications safely through automated pipelines.",
        icon: "rocket",
      },
      {
        id: "observe",
        number: "05",
        title: "Observe",
        description: "Monitor, log and alert in real time for complete visibility.",
        icon: "eye",
      },
      {
        id: "optimize",
        number: "06",
        title: "Optimize",
        description: "Continuously improve performance, reliability and cost efficiency.",
        icon: "growth",
      },
    ],
    architectureLabel: "Architecture around your system",
    architectureVariant: "cloud",
    architectureLayers: [
      {
        id: "applications",
        title: "Your Applications",
        description: "Your digital experiences and operational systems.",
        details: ["Web", "Mobile", "APIs", "Internal Systems"],
        icon: "monitor",
        accent: "green",
      },
      {
        id: "services",
        title: "Application Services",
        description: "Managed services that enable your applications.",
        icon: "settings",
        accent: "blue",
      },
      {
        id: "compute",
        title: "Compute & Containers",
        description: "Scalable compute platforms and container orchestration.",
        icon: "cpu",
        accent: "blue",
      },
      {
        id: "storage",
        title: "Data & Storage",
        description: "Databases, caches, files and object storage.",
        icon: "database",
        accent: "violet",
      },
      {
        id: "networking",
        title: "Networking",
        description: "VPCs, load balancing, DNS and secure connectivity.",
        icon: "network",
        accent: "blue",
      },
      {
        id: "security",
        title: "Security",
        description: "Identity, access, encryption, network and workload security.",
        icon: "shield",
        accent: "coral",
      },
      {
        id: "observability",
        title: "Observability & Recovery",
        description: "Monitoring, logging, backup and disaster recovery.",
        icon: "eye",
        accent: "gold",
      },
    ],
    secondaryLabel: "Deployment models",
    secondaryItems: [
      {
        id: "cloud-native",
        title: "Cloud-native",
        description: "New systems designed directly for the cloud using modern, scalable services.",
        icon: "cloud",
      },
      {
        id: "cloud-migration",
        title: "Cloud migration",
        description: "Move existing workloads to the cloud with minimal risk and maximum value.",
        icon: "cloudUpload",
        accent: "blue",
      },
      {
        id: "hybrid",
        title: "Hybrid infrastructure",
        description: "Connect cloud services with on-premise and edge environments seamlessly.",
        icon: "landmark",
      },
      {
        id: "managed",
        title: "Managed infrastructure",
        description: "We help operate and continuously improve your infrastructure environment.",
        icon: "users",
        accent: "coral",
      },
    ],
    workLabel: "Relevant work",
    work: [
      {
        id: "rembeh-cloud",
        title: "Rembeh",
        category: "Financial Operations Platform",
        description: "Cloud infrastructure designed for high availability, secure data and real-time operations across branches.",
        visual: "rembeh",
        accent: "green",
      },
      {
        id: "carmie-cloud",
        title: "Carmie",
        category: "Automotive Services Platform",
        description: "Scalable infrastructure supporting real-time requests, location services and provider coordination.",
        visual: "carmie",
        accent: "blue",
      },
      {
        id: "client-deployments",
        title: "Client Deployments",
        category: "Enterprise Systems",
        description: "Infrastructure solutions delivered for organizations across financial services, mobility and enterprise operations.",
        visual: "cloud",
        accent: "green",
      },
    ],
    systemLabel: "Delivered through the ANTIKRA system",
    systemDescription: "We combine the right specialists to deliver secure, scalable and reliable infrastructure.",
    systemSpecialists: [specialistCards[1], specialistCards[3], specialistCards[0], specialistCards[2], specialistCards[4]],
    principlesLabel: "Production principles",
    principles: [
      { id: "reliability", title: "Reliability by design", description: "Resilience built into the operating model.", icon: "cloudCog" },
      { id: "security", title: "Security by design", description: "Controls applied across every layer.", icon: "shield" },
      { id: "iac", title: "Infrastructure as code", description: "Repeatable environments and delivery.", icon: "layout" },
      { id: "observability", title: "Observability built-in", description: "Monitoring and insight from day one.", icon: "check" },
      { id: "recovery", title: "Recovery planning", description: "Backup and continuity prepared early.", icon: "serverCog" },
      { id: "cost", title: "Cost awareness", description: "Infrastructure aligned to value.", icon: "growth" },
    ],
    cta: {
      title: "Build on a foundation you can depend on.",
      description: "Let's design and build the infrastructure that powers your next move.",
      buttonLabel: "Discuss your infrastructure",
    },
    next: solutionAreaById["ai-data"],
  },
  "ai-data": {
    id: "ai-data",
    solution: solutionAreaById["ai-data"],
    heading: "AI & Data",
    breadcrumb: "ANTIKRA / Solutions / AI & Data",
    heroIconAccent: "violet",
    visual: "ai",
    lead: "Turn data into decisions, and decisions into action.",
    summary:
      "ANTIKRA builds data and AI systems that help organizations understand operations, predict outcomes, automate decisions and create intelligent products.",
    primaryActionLabel: "Discuss your data & AI needs",
    capabilityLabel: "What we can deliver",
    capabilities: [
      {
        id: "data-platforms",
        title: "Data Platforms",
        description: "Bring fragmented data into governed, secure and scalable platforms.",
        icon: "database",
      },
      {
        id: "analytics-bi",
        title: "Analytics & BI",
        description: "Dashboards, reporting and analytics built around real business decisions.",
        icon: "chart",
      },
      {
        id: "predictive-analytics",
        title: "Predictive Analytics",
        description: "Forecast outcomes, demand, risk and behavior using advanced models.",
        icon: "growth",
      },
      {
        id: "applied-ai",
        title: "Applied AI",
        description: "AI solutions designed to solve specific operational challenges.",
        icon: "brain",
      },
      {
        id: "intelligent-automation",
        title: "Intelligent Automation",
        description: "Use rules, models and AI to reduce manual work and speed up decisions.",
        icon: "network",
      },
      {
        id: "ai-products",
        title: "AI-enabled Products",
        description: "Embed intelligence directly into digital products and workflows.",
        icon: "box",
      },
    ],
    processLabel: "From raw data to operational value",
    process: [
      {
        id: "connect",
        number: "01",
        title: "Connect",
        description: "Connect data from systems, devices and sources.",
        icon: "plug",
      },
      {
        id: "structure",
        number: "02",
        title: "Structure",
        description: "Clean, validate and structure data for reliable use.",
        icon: "list",
      },
      {
        id: "understand",
        number: "03",
        title: "Understand",
        description: "Explore, analyze and understand what the data is telling us.",
        icon: "search",
      },
      {
        id: "model",
        number: "04",
        title: "Model",
        description: "Build models that predict, classify and recommend.",
        icon: "growth",
      },
      {
        id: "deploy",
        number: "05",
        title: "Deploy",
        description: "Deploy models and insights into real operations.",
        icon: "play",
      },
      {
        id: "improve",
        number: "06",
        title: "Improve",
        description: "Continuously learn from outcomes and improve accuracy.",
        icon: "refresh",
      },
    ],
    architectureLabel: "Intelligence architecture",
    architectureVariant: "ai",
    architectureLayers: [
      {
        id: "systems",
        title: "Operational Systems",
        details: ["Apps", "Databases", "APIs", "Files", "Devices"],
        icon: "database",
      },
      {
        id: "ingestion",
        title: "Data Ingestion",
        details: ["Batch", "Streaming", "Real-time"],
        icon: "download",
        accent: "blue",
      },
      {
        id: "platform",
        title: "Data Platform",
        details: ["Storage", "Processing", "Orchestration"],
        icon: "cloud",
        accent: "blue",
      },
      {
        id: "governance",
        title: "Governance & Quality",
        details: ["Catalog", "Lineage", "Quality", "Security"],
        icon: "shield",
        accent: "violet",
      },
      {
        id: "analytics",
        title: "Analytics / ML / AI",
        details: ["Reporting", "ML Models", "AI Services"],
        icon: "brain",
        accent: "violet",
      },
      {
        id: "decision",
        title: "Decision Layer",
        details: ["Rules", "Scores", "Recommendations"],
        icon: "target",
        accent: "coral",
      },
      {
        id: "delivery",
        title: "Dashboards · Automation · API · Products",
        details: ["Insights delivered where decisions happen"],
        icon: "monitor",
      },
    ],
    secondaryLabel: "Applied use cases",
    secondaryItems: [
      {
        id: "credit",
        title: "Credit & Repayment Intelligence",
        description: "Analyze repayment patterns, risk signals and portfolio performance to make better lending decisions.",
        icon: "users",
      },
      {
        id: "demand",
        title: "Demand Forecasting",
        description: "Predict demand by location, service, season or customer behavior to plan resources and capacity.",
        icon: "chart",
        accent: "blue",
      },
      {
        id: "operations",
        title: "Operational Analytics",
        description: "Understand performance across branches, teams, products and processes in real time.",
        icon: "pie",
        accent: "violet",
      },
      {
        id: "anomaly",
        title: "Anomaly Detection",
        description: "Detect unusual transactions, behavior or system activity early and take action.",
        icon: "alert",
        accent: "coral",
      },
      {
        id: "assistant",
        title: "Intelligent Assistance",
        description: "Context-aware assistants that help users get the right answers and recommendations.",
        icon: "message",
      },
      {
        id: "workflow",
        title: "Workflow Automation",
        description: "Automate analysis, approvals and decisions to reduce cycle times and errors.",
        icon: "settings",
        accent: "blue",
      },
    ],
    workLabel: "Relevant work",
    work: [
      {
        id: "rembeh-data",
        title: "Rembeh",
        category: "Financial Operations Platform",
        description: "Using data and analytics to provide portfolio insights, performance reports and smarter risk decisions for microfinance operations.",
        visual: "rembeh",
        accent: "green",
      },
      {
        id: "carmie-data",
        title: "Carmie",
        category: "Automotive Services Platform",
        description: "Operational data across garages, towing and roadside services used to improve response, coverage and performance.",
        visual: "carmie",
        accent: "blue",
      },
      {
        id: "client-data-projects",
        title: "Client Data Projects",
        category: "Analytics & AI Solutions",
        description: "Custom dashboards, predictive models and data platforms delivering measurable impact across multiple sectors.",
        visual: "data",
        accent: "violet",
      },
    ],
    systemLabel: "Delivered through the ANTIKRA system",
    systemDescription: "Specialists working together to turn data into operational advantage.",
    systemSpecialists: [specialistCards[2], specialistCards[0], specialistCards[1], specialistCards[3], specialistCards[4]],
    principlesLabel: "Responsible intelligence",
    principles: [
      { id: "human", title: "Human oversight", description: "People remain accountable for decisions.", icon: "users" },
      { id: "quality", title: "Data quality", description: "Trusted data before advanced models.", icon: "network" },
      { id: "explainability", title: "Explainability (where required)", description: "Reasoning should be understandable.", icon: "monitor" },
      { id: "privacy", title: "Security & privacy", description: "Sensitive data is protected.", icon: "shield" },
      { id: "useful", title: "Measurable usefulness", description: "AI must produce operational value.", icon: "fileCheck" },
    ],
    cta: {
      title: "Put your data to work.",
      description: "Let's turn your data into intelligence that drives measurable results.",
      buttonLabel: "Discuss your data & AI needs",
    },
    next: solutionAreaById.cybersecurity,
  },
  cybersecurity: {
    id: "cybersecurity",
    solution: solutionAreaById.cybersecurity,
    heading: "Cybersecurity",
    breadcrumb: "ANTIKRA / Solutions / Cybersecurity",
    heroIconAccent: "green",
    visual: "security",
    lead: "Security built into everything.",
    summary:
      "ANTIKRA integrates security across applications, infrastructure, identities and data, reducing risk without making technology harder to operate.",
    primaryActionLabel: "Discuss your security needs",
    capabilityLabel: "What we can deliver",
    capabilities: [
      {
        id: "security-architecture",
        title: "Security Architecture",
        description: "Design security requirements and controls into systems from the beginning.",
        icon: "shield",
      },
      {
        id: "application-api-security",
        title: "Application & API Security",
        description: "Protect applications, services, integrations and interfaces through secure engineering and testing.",
        icon: "code",
      },
      {
        id: "cloud-security",
        title: "Cloud & Infrastructure Security",
        description: "Secure workloads, networks, environments and deployment pipelines across cloud and hybrid infrastructure.",
        icon: "cloud",
      },
      {
        id: "identity-access",
        title: "Identity & Access",
        description: "Authentication, authorization, permissions and privileged access done right.",
        icon: "user",
      },
      {
        id: "data-security",
        title: "Data Security",
        description: "Protect data across storage, transmission and use with appropriate controls.",
        icon: "database",
      },
      {
        id: "security-monitoring",
        title: "Security Monitoring",
        description: "Gain visibility with logging, alerting, incident detection and continuous monitoring.",
        icon: "bell",
      },
    ],
    processLabel: "Security across the technology lifecycle",
    process: [
      {
        id: "assess",
        number: "01",
        title: "Assess",
        description: "Understand assets, threats, risks and business impact.",
        icon: "search",
      },
      {
        id: "design",
        number: "02",
        title: "Design",
        description: "Design secure architecture and define controls.",
        icon: "pencil",
      },
      {
        id: "harden",
        number: "03",
        title: "Harden",
        description: "Implement security controls and harden configurations.",
        icon: "shield",
      },
      {
        id: "validate",
        number: "04",
        title: "Validate",
        description: "Test, scan and validate security before release.",
        icon: "check",
      },
      {
        id: "monitor",
        number: "05",
        title: "Monitor",
        description: "Continuously monitor, detect and respond to threats.",
        icon: "monitor",
      },
      {
        id: "improve",
        number: "06",
        title: "Improve",
        description: "Learn and strengthen controls through continuous improvement.",
        icon: "refresh",
      },
    ],
    architectureLabel: "Defense in depth architecture",
    architectureVariant: "security",
    architectureLayers: [
      { id: "users", title: "Users", icon: "users" },
      { id: "identity", title: "Identity & Access", icon: "fingerprint", accent: "blue" },
      { id: "applications", title: "Applications & APIs", icon: "code", accent: "blue" },
      { id: "data", title: "Data Layer", icon: "database" },
      { id: "infrastructure", title: "Infrastructure", icon: "cloud", accent: "blue" },
      { id: "networking", title: "Networking", icon: "network", accent: "blue" },
    ],
    architectureNotes: [
      "Encryption",
      "Access controls",
      "Logging & monitoring",
      "Secure configuration",
      "Vulnerability management",
      "Backup & recovery",
      "Threat detection",
    ],
    secondaryLabel: "Security use cases",
    secondaryItems: [
      {
        id: "new-product",
        title: "Secure a new digital product",
        description: "Embed security throughout architecture, development and deployment.",
        icon: "shield",
      },
      {
        id: "harden",
        title: "Harden an existing platform",
        description: "Identify weaknesses and systematically improve security controls.",
        icon: "growth",
      },
      {
        id: "cloud",
        title: "Protect cloud infrastructure",
        description: "Strengthen environments, networks, identities and workloads in the cloud.",
        icon: "cloud",
      },
      {
        id: "data",
        title: "Secure sensitive data",
        description: "Control access, storage, movement and exposure of critical data.",
        icon: "database",
      },
      {
        id: "identity",
        title: "Identity & permissions",
        description: "Implement strong authentication, role-based access and least privilege principles.",
        icon: "user",
      },
      {
        id: "visibility",
        title: "Security visibility",
        description: "Establish monitoring, logging and actionable alerts across your systems.",
        icon: "eye",
      },
    ],
    workLabel: "Relevant work",
    work: [
      {
        id: "rembeh-security",
        title: "Rembeh",
        category: "Financial Operations Platform",
        description: "Secure platform handling loans, collections and financial data across multiple branches.",
        visual: "rembeh",
        accent: "green",
      },
      {
        id: "carmie-security",
        title: "Carmie",
        category: "Automotive Services Platform",
        description: "Secure infrastructure and applications protecting vehicle owners and service providers.",
        visual: "carmie",
        accent: "blue",
      },
      {
        id: "client-security",
        title: "Client Security Engagements",
        category: "Security Programs",
        description: "Security assessments, architecture reviews and hardening for organizations across multiple sectors.",
        visual: "security",
        accent: "blue",
      },
    ],
    systemLabel: "Delivered through the ANTIKRA system",
    systemDescription: "Cybersecurity is stronger when specialists work together.",
    systemSpecialists: [specialistCards[3], specialistCards[0], specialistCards[1], specialistCards[2], specialistCards[4]],
    principlesLabel: "Security principles",
    principles: [
      { id: "least-privilege", title: "Least privilege", description: "Give access only where needed.", icon: "users" },
      { id: "defense", title: "Defense in depth", description: "Layer controls across the system.", icon: "box" },
      { id: "defaults", title: "Secure defaults", description: "Make secure choices standard.", icon: "lock" },
      { id: "visibility", title: "Continuous visibility", description: "See risk as it changes.", icon: "eye" },
      { id: "data", title: "Data protection", description: "Protect data in every state.", icon: "layout" },
      { id: "resilience", title: "Operational resilience", description: "Prepare systems to recover.", icon: "bell" },
    ],
    cta: {
      title: "Build security into the system - not around it.",
      description: "We help organizations reduce risk and build secure systems that can grow with confidence.",
      buttonLabel: "Discuss your security needs",
    },
    next: solutionAreaById["experience-design"],
  },
  "experience-design": {
    id: "experience-design",
    solution: solutionAreaById["experience-design"],
    heading: "Experience & Design",
    breadcrumb: "ANTIKRA / Solutions / Experience & Design",
    heroIconAccent: "violet",
    themeAccent: "violet",
    visual: "experience",
    lead: "Make complex technology feel simple.",
    summary:
      "ANTIKRA designs digital products and experiences around the people who use them, turning complex workflows into clear, coherent and effective interactions.",
    primaryActionLabel: "Discuss your product",
    capabilityLabel: "What we can deliver",
    capabilities: [
      {
        id: "product-strategy",
        title: "Product Strategy",
        description: "Define the user problem, product direction and experience priorities.",
        icon: "target",
      },
      {
        id: "ux-research",
        title: "UX Research",
        description: "Understand users, environments, workflows and behavioural constraints.",
        icon: "users",
      },
      {
        id: "information-architecture",
        title: "Information Architecture",
        description: "Structure complex information and functionality coherently.",
        icon: "network",
      },
      {
        id: "interaction-design",
        title: "UX & Interaction Design",
        description: "Design workflows and interactions around how people actually work.",
        icon: "cursor",
      },
      {
        id: "interface-design",
        title: "Interface Design",
        description: "Create polished, usable and consistent interfaces.",
        icon: "monitor",
      },
      {
        id: "design-systems",
        title: "Design Systems",
        description: "Build reusable components, patterns and standards that allow products to scale.",
        icon: "layout",
      },
    ],
    processLabel: "From complexity to clarity",
    process: [
      {
        id: "understand",
        number: "1",
        title: "Understand",
        description: "Discover user needs, pain points and opportunities.",
        icon: "user",
      },
      {
        id: "structure",
        number: "2",
        title: "Structure",
        description: "Organize information and define the right experience structure.",
        icon: "list",
      },
      {
        id: "explore",
        number: "3",
        title: "Explore",
        description: "Explore concepts and interaction approaches.",
        icon: "feather",
      },
      {
        id: "prototype",
        number: "4",
        title: "Prototype",
        description: "Build prototypes to bring ideas to life and test early.",
        icon: "play",
      },
      {
        id: "validate",
        number: "5",
        title: "Validate",
        description: "Test with real users and validate what works.",
        icon: "users",
      },
      {
        id: "refine",
        number: "6",
        title: "Refine",
        description: "Refine and iterate until the experience is right.",
        icon: "refresh",
      },
    ],
    architectureLabel: "Design across the product",
    architectureVariant: "experience",
    architectureLayers: [
      { id: "need", title: "User Need", description: "We start with the real needs of real people.", icon: "target", accent: "violet" },
      { id: "ia", title: "Information Architecture", description: "Organize content and functionality logically.", icon: "network", accent: "violet" },
      { id: "workflows", title: "Workflows", description: "Map processes and define clear journeys.", icon: "workflow", accent: "violet" },
      { id: "interaction", title: "Interaction", description: "Design meaningful interactions and behaviors.", icon: "cursor", accent: "violet" },
      { id: "interface", title: "Interface", description: "Create the visual layer users see and use.", icon: "monitor", accent: "violet" },
      { id: "system", title: "Design System", description: "Build consistent components and patterns.", icon: "layout", accent: "violet" },
      { id: "product", title: "Engineered Product", description: "Delivered through robust engineering.", icon: "code", accent: "blue" },
      { id: "feedback", title: "Real-world Feedback", description: "Measure, learn and continuously improve.", icon: "message", accent: "violet" },
    ],
    secondaryLabel: "Designing for different environments",
    secondaryItems: [
      {
        id: "desktop",
        title: "Desktop operations",
        description: "Dense information without overwhelming users.",
        icon: "monitor",
      },
      {
        id: "mobile",
        title: "Mobile & field work",
        description: "Fast workflows for users operating away from desks.",
        icon: "phone",
      },
      {
        id: "low-connectivity",
        title: "Low-connectivity environments",
        description: "Experiences designed around unreliable connectivity.",
        icon: "cloud",
      },
      {
        id: "roles",
        title: "Multi-role systems",
        description: "Different interfaces and permissions for different responsibilities.",
        icon: "users",
      },
      {
        id: "accessibility",
        title: "Accessibility",
        description: "Interfaces usable by a broader range of people.",
        icon: "accessibility",
      },
    ],
    workLabel: "Design in action",
    work: [
      {
        id: "rembeh-design",
        title: "Rembeh",
        category: "Financial Operations Platform",
        description: "Complex financial operations across owners, managers and field agents designed to be clear, consistent and operationally effective.",
        visual: "design",
        accent: "violet",
      },
      {
        id: "carmie-design",
        title: "Carmie",
        category: "Automotive Services Platform",
        description: "Location-aware automotive workflows connecting motorists and service providers across the journey.",
        visual: "carmie",
        accent: "blue",
      },
    ],
    systemLabel: "Delivered through the ANTIKRA system",
    systemDescription: "Design is strongest when it is connected to engineering, intelligence, security and reliable delivery.",
    systemSpecialists: [specialistCards[4], specialistCards[0], specialistCards[2], specialistCards[3], specialistCards[1]],
    principlesLabel: "Design principles",
    principles: [
      { id: "clarity", title: "Clarity over decoration", description: "Every screen must make work easier.", icon: "brain" },
      { id: "context", title: "Context before assumptions", description: "Understand the environment before designing.", icon: "box" },
      { id: "consistency", title: "Consistency at scale", description: "Systems should behave predictably.", icon: "layout" },
      { id: "accessibility", title: "Accessibility by default", description: "Usability should include more people.", icon: "accessibility" },
      { id: "evidence", title: "Evidence over preference", description: "Decisions should be grounded in use.", icon: "users" },
      { id: "refinement", title: "Continuous refinement", description: "Design improves with feedback.", icon: "feather" },
    ],
    cta: {
      title: "Design technology people can actually use.",
      description: "Great design makes complex systems simple, usable and valuable.",
      buttonLabel: "Discuss your product",
    },
    next: solutionAreaById["venture-building"],
  },
  "venture-building": {
    id: "venture-building",
    solution: solutionAreaById["venture-building"],
    heading: "Venture Building",
    breadcrumb: "ANTIKRA / Solutions / Venture Building",
    heroIconAccent: "teal",
    themeAccent: "teal",
    visual: "venture",
    lead: "Turn an opportunity into an operating company.",
    summary:
      "ANTIKRA combines venture design, product engineering and specialist technology capabilities to take promising opportunities from validation through launch and early growth.",
    primaryActionLabel: "Discuss an opportunity",
    capabilityLabel: "What we help build",
    capabilities: [
      {
        id: "new-technology-ventures",
        title: "New Technology Ventures",
        description: "Build a technology company around a validated market problem.",
        icon: "rocket",
      },
      {
        id: "corporate-ventures",
        title: "Corporate Ventures",
        description: "Help established organizations create new digital businesses outside their existing operating model.",
        icon: "building",
      },
      {
        id: "digital-businesses",
        title: "Digital Products as Businesses",
        description: "Turn a software or product opportunity into a commercially structured and scalable venture.",
        icon: "box",
      },
      {
        id: "modernization",
        title: "Venture Modernization",
        description: "Help an existing early-stage business strengthen its product and technology foundation.",
        icon: "refresh",
      },
    ],
    processLabel: "From hypothesis to company",
    process: [
      {
        id: "discover",
        number: "01",
        title: "Discover",
        description: "Problem discovery, opportunity framing, initial research and hypothesis.",
        icon: "compass",
      },
      {
        id: "validate",
        number: "02",
        title: "Validate",
        description: "Customer evidence, market assessment, assumptions and feasibility.",
        icon: "check",
      },
      {
        id: "define",
        number: "03",
        title: "Define",
        description: "Business model, product proposition, operating model and brand direction.",
        icon: "clipboard",
      },
      {
        id: "build",
        number: "04",
        title: "Build",
        description: "Product, infrastructure, security, experience and data foundation.",
        icon: "code",
      },
      {
        id: "launch",
        number: "05",
        title: "Launch",
        description: "Go-to-market, early users, feedback loops and traction.",
        icon: "rocket",
      },
      {
        id: "grow",
        number: "06",
        title: "Grow",
        description: "Product evolution, operations, partnerships and financial growth.",
        icon: "growth",
      },
    ],
    architectureLabel: "One venture. The ANTIKRA system behind it.",
    architectureVariant: "venture",
    architectureLayers: [
      { id: "olympia", title: "Olympia", description: "Venture Building", icon: "landmark", accent: "teal" },
      { id: "helios", title: "Helios", description: "Experience & Design", icon: "sun", accent: "coral" },
      { id: "mechanism", title: "Mechanism", description: "Product Engineering", icon: "box", accent: "green" },
      { id: "cosmos", title: "Cosmos", description: "Infrastructure & Operations", icon: "cloud", accent: "blue" },
      { id: "orrery", title: "Orrery", description: "Data & Intelligence", icon: "orbit", accent: "violet" },
      { id: "astra", title: "Astra", description: "Security", icon: "shield", accent: "blue" },
    ],
    secondaryLabel: "What ANTIKRA brings",
    secondaryItems: [
      {
        id: "strategy",
        title: "Venture Strategy",
        description: "Opportunity, proposition and business-model development.",
        icon: "target",
      },
      {
        id: "product",
        title: "Product",
        description: "Strategy, UX, engineering and product evolution.",
        icon: "code",
      },
      {
        id: "technology",
        title: "Technology",
        description: "Architecture, infrastructure, security and data.",
        icon: "cloud",
      },
      {
        id: "brand",
        title: "Brand & Experience",
        description: "Identity, positioning and customer experience design.",
        icon: "alert",
        accent: "coral",
      },
      {
        id: "foundation",
        title: "Operating Foundation",
        description: "Systems, processes and structures needed to operate the venture.",
        icon: "landmark",
      },
      {
        id: "development",
        title: "Continuous Development",
        description: "Product and technology support as the business learns and grows.",
        icon: "refresh",
      },
    ],
    workLabel: "Ventures built within the system",
    work: [
      {
        id: "rembeh-venture",
        title: "Rembeh",
        category: "Financial Technology",
        description: "A financial operations platform simplifying complex loan management for organizations and their teams.",
        visual: "rembeh",
        accent: "green",
      },
      {
        id: "carmie-venture",
        title: "Carmie",
        category: "Automotive Technology",
        description: "A location-aware platform connecting motorists and service providers for roadside assistance and automotive services.",
        visual: "carmie",
        accent: "blue",
      },
    ],
    systemLabel: "Ways to build with us",
    systemDescription: "ANTIKRA can build around a new opportunity, a corporate venture or a deeper venture-building relationship.",
    systemSpecialists: [specialistCards[5], specialistCards[4], specialistCards[0], specialistCards[1], specialistCards[2], specialistCards[3]],
    principlesLabel: "What happens before we build",
    principles: [
      { id: "problem", title: "Problem significance", description: "The problem is worth solving.", icon: "target" },
      { id: "customer", title: "Customer evidence", description: "Real users show real need.", icon: "users" },
      { id: "market", title: "Market potential", description: "The opportunity can support growth.", icon: "growth" },
      { id: "business", title: "Business viability", description: "The model can work commercially.", icon: "shield" },
      { id: "technical", title: "Technical feasibility", description: "The product can be built and operated.", icon: "settings" },
      { id: "fit", title: "Strategic fit", description: "The venture belongs in the ANTIKRA system.", icon: "lightbulb" },
    ],
    cta: {
      title: "From capability to evidence.",
      description: "Explore the ventures, platforms and solutions ANTIKRA has built and delivered.",
      buttonLabel: "See what we've built",
    },
    next: solutionAreaById["product-engineering"],
  },
}
