import type { CompanyPageContent } from "./models"

export const companyPages: Record<CompanyPageContent["id"], CompanyPageContent> = {
  mechanism: {
    id: "mechanism",
    number: "01",
    total: "06",
    name: "Mechanism",
    breadcrumb: "ANTIKRA / Companies / Mechanism",
    discipline: "Product Engineering",
    summary:
      "We design, engineer and operate digital products built for real-world complexity.",
    accent: "bronze",
    icon: "box",
    visualKind: "mechanism",
    visualNotes: [
      "Scalable\nSecure\nReliable",
      "Human-centred\nPerformance-driven\nFuture-ready",
      "Engineering\nwith precision.\nDelivering\nwith impact.",
    ],
    capabilityLabel: "What Mechanism does",
    workLabel: "Selected products & work",
    processLabel: "How we build",
    capabilities: [
      {
        id: "product-strategy",
        title: "Product Strategy",
        description: "We help define the right problems and build the right things.",
        icon: "radar",
      },
      {
        id: "software-engineering",
        title: "Software Engineering",
        description: "Robust, scalable and maintainable software that performs.",
        icon: "network",
      },
      {
        id: "web-applications",
        title: "Web Applications",
        description: "Modern web apps built for speed, security and scale.",
        icon: "screen",
      },
      {
        id: "mobile-applications",
        title: "Mobile Applications",
        description: "Intuitive mobile experiences for iOS and Android.",
        icon: "phone",
      },
      {
        id: "enterprise-systems",
        title: "Enterprise Systems",
        description: "Business systems that streamline operations.",
        icon: "briefcase",
      },
      {
        id: "platform-engineering",
        title: "Platform Engineering",
        description: "Reusable platforms and tools that accelerate delivery.",
        icon: "database",
      },
      {
        id: "systems-integration",
        title: "Systems Integration",
        description: "Seamless integration with your critical systems and data.",
        icon: "nodes",
      },
    ],
    selectedWork: [
      {
        id: "rembeh",
        title: "Rembeh",
        description: "Financial operations infrastructure for lending businesses.",
        linkLabel: "View product",
        visual: "rembeh",
        accent: "green",
      },
      {
        id: "carmie",
        title: "Carmie",
        description: "Infrastructure for the automotive service economy.",
        linkLabel: "View product",
        visual: "carmie",
        accent: "blue",
      },
      {
        id: "client-work",
        title: "Selected Client Work",
        description: "Custom systems and platforms delivered for organizations across industries.",
        linkLabel: "View case studies",
        visual: "client",
        accent: "bronze",
      },
    ],
    process: [
      {
        id: "discover",
        title: "Discover",
        description: "We understand your goals, users and challenges.",
        icon: "radar",
      },
      {
        id: "architect",
        title: "Architect",
        description: "We design the right solution architecture and roadmap.",
        icon: "box",
      },
      {
        id: "design",
        title: "Design",
        description: "We craft intuitive, usable and delightful experiences.",
        icon: "pencil",
      },
      {
        id: "engineer",
        title: "Engineer",
        description: "We build clean, secure and scalable software.",
        icon: "nodes",
      },
      {
        id: "deploy",
        title: "Deploy",
        description: "We deploy with precision and minimal disruption.",
        icon: "rocket",
      },
      {
        id: "evolve",
        title: "Evolve",
        description: "We monitor, improve and evolve with your business.",
        icon: "growth",
      },
    ],
    capabilityList: [
      "Frontend Engineering",
      "Backend Engineering",
      "Mobile Development",
      "APIs & Integrations",
      "Databases & Data",
      "System Architecture",
      "DevOps Collaboration",
      "Quality Engineering",
      "Technical Consulting",
    ],
    partners: [
      {
        id: "helios",
        title: "Mechanism + Helios",
        description: "Design + Engineering",
        icon: "sun",
        accent: "coral",
      },
      {
        id: "cosmos",
        title: "Mechanism + Cosmos",
        description: "Engineering + Infrastructure",
        icon: "cloud",
        accent: "green",
      },
      {
        id: "orrery",
        title: "Mechanism + Orrery",
        description: "Software + Intelligence",
        icon: "orbit",
        accent: "violet",
      },
      {
        id: "astra",
        title: "Mechanism + Astra",
        description: "Engineering + Security",
        icon: "shield",
        accent: "blue",
      },
    ],
    technologies: ["TypeScript", "React", "Next.js", "Node.js", "Python", "PostgreSQL", "AWS"],
    cta: {
      eyebrow: "Start a project with Mechanism",
      title: "Have a product or system to build?",
      description: "Let's design and build what's next.",
      buttonLabel: "Discuss your project",
    },
    next: {
      number: "02",
      total: "06",
      name: "Cosmos",
      discipline: "Cloud & Infrastructure",
      href: "/companies/cosmos",
      accent: "green",
      visualKind: "cosmos",
    },
  },
  cosmos: {
    id: "cosmos",
    number: "02",
    total: "06",
    name: "Cosmos",
    breadcrumb: "ANTIKRA / Companies / Cosmos",
    discipline: "Cloud & Infrastructure",
    summary:
      "Infrastructure engineered to keep digital systems available, secure and ready to scale.",
    accent: "green",
    icon: "cloud",
    visualKind: "cosmos",
    visualNotes: [
      "Built for scale\nDesigned for\nreliability",
      "Secure by design\nResilient by\narchitecture",
      "Operational\nexcellence\nEvery layer",
    ],
    capabilityLabel: "What Cosmos delivers",
    workLabel: "Selected infrastructure & platform work",
    processLabel: "How we operate",
    capabilities: [
      {
        id: "cloud-architecture",
        title: "Cloud Architecture",
        description: "Designing cloud-native architectures that are secure, scalable and cost-efficient.",
        icon: "cloud",
      },
      {
        id: "infrastructure-engineering",
        title: "Infrastructure Engineering",
        description: "Building robust, flexible infrastructure that forms the foundation of your systems.",
        icon: "database",
      },
      {
        id: "devops-automation",
        title: "DevOps & Automation",
        description: "Automating delivery pipelines and operations for speed, consistency and quality.",
        icon: "infinity",
      },
      {
        id: "deployment-release",
        title: "Deployment & Release",
        description: "Reliable deployment strategies that minimize risk and maximize velocity.",
        icon: "rocket",
      },
      {
        id: "reliability-observability",
        title: "Reliability & Observability",
        description: "Monitoring, logging and alerting that give you full visibility and control.",
        icon: "chart",
      },
      {
        id: "infrastructure-operations",
        title: "Infrastructure Operations",
        description: "24/7 operations, incident management and continuous improvement at every layer.",
        icon: "user",
      },
    ],
    selectedWork: [
      {
        id: "powering-rembeh",
        title: "Powering Rembeh",
        description: "Cloud infrastructure that supports thousands of daily transactions across branches.",
        linkLabel: "View case study",
        visual: "rembeh",
        accent: "green",
      },
      {
        id: "powering-carmie",
        title: "Powering Carmie",
        description: "Scalable infrastructure that keeps the automotive service ecosystem connected.",
        linkLabel: "View case study",
        visual: "carmie",
        accent: "blue",
      },
      {
        id: "client-infrastructure",
        title: "Client Infrastructure",
        description: "Designing and operating secure, high-availability infrastructure for enterprise systems.",
        linkLabel: "View case study",
        visual: "datacenter",
        accent: "green",
      },
    ],
    process: [
      {
        id: "architect",
        title: "Architect",
        description: "We design the right infrastructure for your requirements.",
        icon: "radar",
      },
      {
        id: "provision",
        title: "Provision",
        description: "We set up secure, scalable environments as code.",
        icon: "box",
      },
      {
        id: "deploy",
        title: "Deploy",
        description: "We release with confidence using automated pipelines.",
        icon: "rocket",
      },
      {
        id: "observe",
        title: "Observe",
        description: "We monitor and gain insights across all layers.",
        icon: "search",
      },
      {
        id: "protect",
        title: "Protect",
        description: "We implement security controls and ensure compliance.",
        icon: "shield",
      },
      {
        id: "scale",
        title: "Scale",
        description: "We optimize and scale infrastructure as your business grows.",
        icon: "growth",
      },
    ],
    capabilityList: [
      "Cloud Architecture",
      "Security & Compliance",
      "Infrastructure as Code",
      "Networking",
      "Containerization",
      "Backup & DR",
      "Kubernetes",
      "Cost Optimization",
      "CI/CD Automation",
    ],
    partners: [
      {
        id: "mechanism",
        title: "Cosmos + Mechanism",
        description: "Infrastructure + Engineering",
        icon: "box",
        accent: "bronze",
      },
      {
        id: "orrery",
        title: "Cosmos + Orrery",
        description: "Infrastructure + Intelligence",
        icon: "orbit",
        accent: "violet",
      },
      {
        id: "astra",
        title: "Cosmos + Astra",
        description: "Infrastructure + Security",
        icon: "shield",
        accent: "blue",
      },
      {
        id: "helios",
        title: "Cosmos + Helios",
        description: "Infrastructure + Experience",
        icon: "sun",
        accent: "coral",
      },
    ],
    technologies: ["AWS", "Azure", "Google Cloud", "Kubernetes", "Terraform", "Docker"],
    metrics: [
      { value: "99.95%", label: "Infrastructure uptime across environments" },
      { value: "24/7", label: "Infrastructure monitoring & incident response" },
      { value: "Scalable", label: "From startup to enterprise and beyond" },
    ],
    cta: {
      eyebrow: "Build with Cosmos",
      title: "Ready to build on a reliable foundation?",
      description: "Let's design infrastructure that scales with your ambitions.",
      buttonLabel: "Discuss your infrastructure needs",
    },
    next: {
      number: "03",
      total: "06",
      name: "Orrery",
      discipline: "AI & Data",
      href: "/companies/orrery",
      accent: "violet",
      visualKind: "orrery",
    },
  },
  orrery: {
    id: "orrery",
    number: "03",
    total: "06",
    name: "Orrery",
    breadcrumb: "ANTIKRA / Companies / Orrery",
    discipline: "AI & Data",
    lead: "Intelligence engineered from data.",
    summary:
      "We design data systems and intelligent technologies that turn information into prediction, automation and better decisions.",
    accent: "violet",
    icon: "orbit",
    visualKind: "orrery",
    visualNotes: [
      "Data Sources\nApplications\nDatabases\nAPIs",
      "Modeling & Intelligence\nMachine learning\nAI models\nValidation",
      "Insights & Actions\nDashboards\nPredictions\nAutomations",
    ],
    capabilityLabel: "What Orrery delivers",
    workLabel: "Intelligence in action",
    workLinkLabel: null,
    processLabel: "How we build intelligence",
    capabilities: [
      {
        id: "data-engineering",
        title: "Data Engineering",
        description: "Build robust data pipelines and platforms that turn raw data into trusted, ready-to-use assets.",
        icon: "database",
      },
      {
        id: "analytics-bi",
        title: "Analytics & BI",
        description: "Transform data into clear insights and interactive dashboards for confident decision-making.",
        icon: "chart",
      },
      {
        id: "machine-learning",
        title: "Machine Learning",
        description: "Design, train and deploy models that predict, classify and uncover what matters.",
        icon: "networkNodes",
      },
      {
        id: "applied-ai",
        title: "Applied AI",
        description: "Build intelligent systems that learn from data and solve real-world problems.",
        icon: "sparkles",
      },
      {
        id: "intelligent-automation",
        title: "Intelligent Automation",
        description: "Automate decisions and workflows with AI to increase efficiency and reduce error.",
        icon: "bot",
      },
      {
        id: "ai-integration",
        title: "AI Integration",
        description: "Seamlessly integrate AI capabilities into products, platforms and business processes.",
        icon: "puzzle",
      },
    ],
    selectedWork: [
      {
        id: "smarter-collections-rembeh",
        title: "Smarter Collections with Rembeh",
        description:
          "Predict repayment behavior and build platforms that turn raw data into machine-ready assets.",
        linkLabel: "View use case",
        visual: "analytics",
        accent: "green",
      },
      {
        id: "service-demand-carmie",
        title: "Service Demand Intelligence with Carmie",
        description:
          "Forecast service demand, optimize resource allocation and personalize customer experiences.",
        linkLabel: "View use case",
        visual: "carmie",
        accent: "blue",
      },
      {
        id: "client-analytics-reporting",
        title: "Client Analytics & Reporting",
        description:
          "Unified analytics platforms that give organizations a single source of truth and reduce operational friction.",
        linkLabel: "View case studies",
        visual: "analytics",
        accent: "violet",
      },
    ],
    process: [
      {
        id: "discover",
        title: "Discover",
        description: "We understand your goals, questions and the data behind them.",
        icon: "compass",
      },
      {
        id: "structure",
        title: "Structure",
        description: "We design the data architecture and prepare high-quality datasets.",
        icon: "grid",
      },
      {
        id: "model",
        title: "Model",
        description: "We build and train models that learn patterns and generate predictions.",
        icon: "networkNodes",
      },
      {
        id: "validate",
        title: "Validate",
        description: "We test, evaluate and refine for accuracy, fairness and reliability.",
        icon: "circleCheck",
      },
      {
        id: "deploy",
        title: "Deploy",
        description: "We put models into production and integrate with your systems.",
        icon: "cloudUpload",
      },
      {
        id: "learn",
        title: "Learn",
        description: "We monitor performance and continuously improve as data evolves.",
        icon: "refresh",
      },
    ],
    capabilityList: [
      "Data Strategy & Governance",
      "Machine Learning",
      "Data Engineering & Pipelines",
      "Natural Language Processing",
      "Data Warehousing & Lakehouse",
      "Computer Vision",
      "Analytics & Visualization",
      "MLOps & Model Operations",
    ],
    partners: [
      {
        id: "mechanism",
        title: "Orrery + Mechanism",
        description: "Intelligence + Engineering",
        icon: "box",
        accent: "bronze",
      },
      {
        id: "cosmos",
        title: "Orrery + Cosmos",
        description: "Intelligence + Infrastructure",
        icon: "cloud",
        accent: "green",
      },
      {
        id: "astra",
        title: "Orrery + Astra",
        description: "Intelligence + Security",
        icon: "shield",
        accent: "blue",
      },
      {
        id: "helios",
        title: "Orrery + Helios",
        description: "Intelligence + Experience",
        icon: "sun",
        accent: "coral",
      },
    ],
    technologies: [
      "Python",
      "Spark",
      "dbt",
      "BigQuery",
      "Snowflake",
      "TensorFlow",
      "PyTorch",
      "Airflow",
      "Pandas",
      "Kubernetes",
    ],
    technologyLabel: "Technologies we work with",
    metrics: [
      {
        title: "Data into Decisions",
        value: "10M+",
        label: "Records processed daily",
      },
      {
        title: "Model Accuracy",
        value: "92%+",
        label: "Across production models",
      },
      {
        title: "Operational Impact",
        value: "30%+",
        label: "Efficiency improvement on average",
      },
    ],
    cta: {
      eyebrow: "Data advantage",
      title: "Turn your data into your advantage.",
      description: "Let's build intelligent systems that drive measurable impact.",
      buttonLabel: "Discuss your data & AI needs",
    },
    next: {
      number: "04",
      total: "06",
      name: "Astra",
      discipline: "Cybersecurity",
      href: "/companies/astra",
      accent: "blue",
      visualKind: "astra",
    },
  },
  astra: {
    id: "astra",
    number: "04",
    total: "06",
    name: "Astra",
    breadcrumb: "ANTIKRA / Companies / Astra",
    discipline: "Cybersecurity",
    lead: "Security engineered into the system.",
    summary:
      "We protect applications, infrastructure and data by embedding security across the technology lifecycle.",
    accent: "blue",
    icon: "shield",
    visualKind: "astra",
    visualNotes: [
      "Identity & Access\nPeople & Access\nManagement",
      "Applications & APIs\nSecure code, services\nand integrations",
      "Monitor & Respond\nDetect threats and\nrespond in real time",
    ],
    capabilityLabel: "What Astra protects",
    workLabel: "Security in action",
    workLinkLabel: "View all case studies",
    processLabel: "How we secure systems",
    capabilities: [
      {
        id: "application-security",
        title: "Application Security",
        description: "Secure software development, code analysis and runtime protection.",
        icon: "shieldCheck",
      },
      {
        id: "cloud-security",
        title: "Cloud Security",
        description: "Secure cloud architectures, workloads, configurations and containers.",
        icon: "cloud",
      },
      {
        id: "data-security",
        title: "Data Security",
        description: "Protect data at rest, in transit and in use with encryption and access controls.",
        icon: "database",
      },
      {
        id: "identity-access",
        title: "Identity & Access",
        description: "Manage identities, permissions and privileged access with strong controls.",
        icon: "key",
      },
      {
        id: "security-monitoring",
        title: "Security Monitoring",
        description: "Continuous monitoring, threat detection and anomaly analysis across environments.",
        icon: "chart",
      },
      {
        id: "risk-compliance",
        title: "Risk & Compliance",
        description: "Assess risk, maintain compliance and meet regulatory and audit requirements.",
        icon: "file",
      },
    ],
    selectedWork: [
      {
        id: "securing-rembeh",
        title: "Securing Rembeh",
        description:
          "Protecting financial operations with secure authentication, role-based access and encrypted data.",
        linkLabel: "View case study",
        visual: "security",
        accent: "green",
      },
      {
        id: "securing-carmie",
        title: "Securing Carmie",
        description:
          "Securing customer data, transactions and platform integrations across the automotive ecosystem.",
        linkLabel: "View case study",
        visual: "carmie",
        accent: "blue",
      },
      {
        id: "infrastructure-protection",
        title: "Infrastructure Protection",
        description:
          "Hardening cloud and infrastructure environments to ensure availability, resilience and compliance.",
        linkLabel: "View case study",
        visual: "datacenter",
        accent: "blue",
      },
    ],
    process: [
      {
        id: "assess",
        title: "1. Assess",
        description: "Identify assets, risks and security gaps.",
        icon: "radar",
      },
      {
        id: "architect",
        title: "2. Architect",
        description: "Design secure architectures and reference controls.",
        icon: "grid",
      },
      {
        id: "harden",
        title: "3. Harden",
        description: "Implement controls, secure configurations and protective layers.",
        icon: "shieldCheck",
      },
      {
        id: "monitor",
        title: "4. Monitor",
        description: "Continuously monitor systems, users and threat indicators.",
        icon: "chart",
      },
      {
        id: "respond",
        title: "5. Respond",
        description: "Detect, investigate and respond to security incidents quickly.",
        icon: "bolt",
      },
      {
        id: "improve",
        title: "6. Improve",
        description: "Learn from events and continuously strengthen your security posture.",
        icon: "refresh",
      },
    ],
    capabilityListLabel: "Our core capabilities",
    capabilityList: [
      "Vulnerability Management",
      "Threat Detection & Hunting",
      "Identity & Access Management",
      "Incident Response",
      "Secure Architecture",
      "Security Testing",
      "API Security",
      "Governance & Compliance",
    ],
    partners: [
      {
        id: "mechanism",
        title: "Astra + Mechanism",
        description: "Secure Engineering",
        icon: "box",
        accent: "bronze",
      },
      {
        id: "cosmos",
        title: "Astra + Cosmos",
        description: "Infrastructure Security",
        icon: "cloud",
        accent: "green",
      },
      {
        id: "orrery",
        title: "Astra + Orrery",
        description: "Data & AI Security",
        icon: "orbit",
        accent: "violet",
      },
      {
        id: "helios",
        title: "Astra + Helios",
        description: "Secure Experience",
        icon: "sun",
        accent: "coral",
      },
    ],
    technologies: ["AWS", "Azure", "Terraform", "Kubernetes", "Snyk", "Wiz", "Okta", "Splunk"],
    technologyLabel: "Technologies & tools we use",
    metrics: [
      { value: "24/7", label: "Security monitoring across environments" },
      { value: "99.9%", label: "Continuous protection and detection" },
      { value: "Reduced Risk", label: "Proactive approach that reduces exposure" },
    ],
    cta: {
      eyebrow: "Security by design",
      title: "Security is not a product. It's our promise.",
      description:
        "We help you build, run and grow with confidence by keeping your systems resilient and your data safe.",
      buttonLabel: "Talk to our security team",
    },
    next: {
      number: "05",
      total: "06",
      name: "Helios",
      discipline: "Experience & Design",
      href: "/companies/helios",
      accent: "coral",
      visualKind: "helios",
    },
  },
  helios: {
    id: "helios",
    number: "05",
    total: "06",
    name: "Helios",
    breadcrumb: "ANTIKRA / Companies / Helios",
    discipline: "Experience & Design",
    lead: "Complex technology, made intuitive.",
    summary:
      "We design digital experiences, interfaces and brand systems that make technology clear, useful and desirable.",
    accent: "coral",
    icon: "sun",
    visualKind: "helios",
    visualNotes: [
      "Research\nUnderstand users\nand context",
      "Design\nInterfaces\n& components",
      "Deliver\nBeautiful experiences\nthat perform",
    ],
    capabilityLabel: "What Helios delivers",
    workLabel: "Design in action",
    workLinkLabel: "View all projects",
    processLabel: "How we design",
    capabilities: [
      {
        id: "product-design",
        title: "Product Design",
        description: "Shape products that solve real problems and create lasting value.",
        icon: "compass",
      },
      {
        id: "ux-research",
        title: "UX Research",
        description: "Uncover user insights and translate them into meaningful opportunities.",
        icon: "search",
      },
      {
        id: "ui-design",
        title: "UI Design",
        description: "Craft clean, beautiful interfaces that are easy to use.",
        icon: "screen",
      },
      {
        id: "design-systems",
        title: "Design Systems",
        description: "Build consistent, scalable systems that accelerate delivery.",
        icon: "layers",
      },
      {
        id: "brand-identity",
        title: "Brand & Identity",
        description: "Create brand systems that express clarity, credibility and purpose.",
        icon: "palette",
      },
      {
        id: "digital-experience",
        title: "Digital Experience",
        description: "Design end-to-end experiences across all touchpoints.",
        icon: "phone",
      },
    ],
    selectedWork: [
      {
        id: "rembeh-design",
        title: "Rembeh",
        description:
          "Financial operations platform designed as a clean, efficient interface for branches and managers.",
        linkLabel: "View project",
        visual: "rembeh",
        accent: "green",
      },
      {
        id: "carmie-design",
        title: "Carmie",
        description:
          "Automotive services platform designed to connect vehicle owners with garages and towing providers.",
        linkLabel: "View project",
        visual: "carmie",
        accent: "blue",
      },
      {
        id: "client-experience-projects",
        title: "Client Experience Projects",
        description: "Digital experiences and brand systems for organizations across industries.",
        linkLabel: "View case studies",
        visual: "design",
        accent: "coral",
      },
    ],
    process: [
      {
        id: "understand",
        title: "1. Understand",
        description: "We learn your users, goals and challenges.",
        icon: "compass",
      },
      {
        id: "define",
        title: "2. Define",
        description: "We define problems and success metrics.",
        icon: "file",
      },
      {
        id: "explore",
        title: "3. Explore",
        description: "We explore ideas and experience opportunities.",
        icon: "eye",
      },
      {
        id: "prototype",
        title: "4. Prototype",
        description: "We prototype solutions to test and iterate quickly.",
        icon: "screen",
      },
      {
        id: "validate",
        title: "5. Validate",
        description: "We validate with users and measure what matters.",
        icon: "users",
      },
      {
        id: "refine",
        title: "6. Refine",
        description: "We refine and deliver polished experiences that scale.",
        icon: "refresh",
      },
    ],
    capabilityList: [
      "UX Strategy",
      "Interaction Design",
      "Design Systems",
      "User Research",
      "UI Design",
      "Accessibility",
      "Information Architecture",
      "Prototyping & Testing",
      "Brand Systems",
    ],
    partners: [
      {
        id: "mechanism",
        title: "Helios + Mechanism",
        description: "Design + Engineering",
        icon: "box",
        accent: "bronze",
      },
      {
        id: "orrery",
        title: "Helios + Orrery",
        description: "Design + Intelligence",
        icon: "orbit",
        accent: "violet",
      },
      {
        id: "cosmos",
        title: "Helios + Cosmos",
        description: "Design + Infrastructure",
        icon: "cloud",
        accent: "green",
      },
      {
        id: "astra",
        title: "Helios + Astra",
        description: "Design + Security",
        icon: "shield",
        accent: "blue",
      },
    ],
    technologies: ["Figma", "Sketch", "Adobe XD", "Photoshop", "Illustrator", "InVision", "Miro"],
    technologyLabel: "Tools & technologies we use",
    technologyLinkLabel: "See full toolset",
    metrics: [
      { value: "User-Centered", label: "Every decision anchored in user needs." },
      { value: "Clear & Usable", label: "Interfaces that are easy to learn and love." },
      { value: "Business Impact", label: "Experiences that drive adoption and results." },
    ],
    cta: {
      eyebrow: "Experience systems",
      title: "Design experiences people understand and trust.",
      description: "Let's create clarity, connection and impact.",
      buttonLabel: "Let's talk design",
    },
    next: {
      number: "06",
      total: "06",
      name: "Olympia",
      discipline: "Ventures",
      href: "/companies/olympia",
      accent: "green",
      visualKind: "olympia",
    },
  },
  olympia: {
    id: "olympia",
    number: "06",
    total: "06",
    name: "Olympia",
    breadcrumb: "ANTIKRA / Companies / Olympia",
    discipline: "Ventures",
    lead: "We build companies around consequential problems.",
    summary:
      "Olympia identifies opportunities, validates new business models and builds technology ventures using the capabilities of the ANTIKRA group.",
    accent: "green",
    icon: "venture",
    visualKind: "olympia",
    visualNotes: [
      "Opportunity\nSpot a problem\nworth solving",
      "Launch\nGo to market &\nonboard users",
      "Scale\nGrow impact\n& value",
    ],
    primaryActionLabel: "Explore our ventures",
    secondaryActionLabel: "Build with Olympia",
    capabilityLabel: "What Olympia does",
    workLabel: "Ventures built within ANTIKRA",
    processLabel: "How we build ventures",
    capabilities: [
      {
        id: "venture-discovery",
        title: "Venture Discovery",
        description: "Identify underserved problems and market opportunities.",
        icon: "compass",
      },
      {
        id: "validation",
        title: "Validation",
        description: "Test demand, economics and feasibility before committing resources.",
        icon: "search",
      },
      {
        id: "venture-design",
        title: "Venture Design",
        description: "Define the business model, product, brand and operating structure.",
        icon: "file",
      },
      {
        id: "venture-building",
        title: "Venture Building",
        description: "Use ANTIKRA companies to engineer and launch the technology.",
        icon: "box",
      },
      {
        id: "growth",
        title: "Growth",
        description: "Develop distribution, operations and commercial capability.",
        icon: "growth",
      },
      {
        id: "portfolio-development",
        title: "Portfolio Development",
        description: "Continue supporting and governing ventures after launch.",
        icon: "shield",
      },
    ],
    selectedWork: [],
    ventureWork: [
      {
        id: "rembeh",
        name: "Rembeh",
        category: "Financial Technology",
        description: "Financial operations infrastructure for lending businesses.",
        details: [
          { label: "Status", value: "Operating" },
          { label: "Market", value: "Uganda" },
          { label: "Users", value: "500+ branches" },
        ],
        builtWith: ["Mechanism", "Cosmos", "Helios", "Astra"],
        linkLabel: "Explore Rembeh",
        visual: "rembeh",
        accent: "green",
      },
      {
        id: "carmie",
        name: "Carmie",
        category: "Automotive Services",
        description: "Digital platform connecting vehicle owners with garages and towing providers.",
        details: [
          { label: "Status", value: "Operating" },
          { label: "Market", value: "Uganda" },
          { label: "Users", value: "150+ garages + 150+ tow providers" },
        ],
        builtWith: ["Mechanism", "Cosmos", "Helios", "Astra"],
        linkLabel: "Explore Carmie",
        visual: "carmie",
        accent: "blue",
      },
      {
        id: "pipeline",
        name: "More ventures in build",
        category: "Portfolio pipeline",
        description:
          "Olympia is continuously evaluating and building new ventures across industries that create real impact.",
        bullets: [
          "Digital Infrastructure",
          "Enterprise Software",
          "Financial Inclusion",
          "Mobility & Logistics",
          "Clean Energy",
          "Data & Intelligence",
        ],
        linkLabel: "See our approach",
        visual: "venture",
        accent: "green",
      },
    ],
    process: [
      {
        id: "discover",
        title: "1. Discover",
        description: "Uncover problems, opportunities and initial signals.",
        icon: "compass",
      },
      {
        id: "validate",
        title: "2. Validate",
        description: "Validate demand, market size and unit economics.",
        icon: "check",
      },
      {
        id: "design",
        title: "3. Design",
        description: "Design the business, product and operating model.",
        icon: "file",
      },
      {
        id: "build",
        title: "4. Build",
        description: "Build product, team, infrastructure and go-to-market.",
        icon: "box",
      },
      {
        id: "launch",
        title: "5. Launch",
        description: "Launch the venture, acquire customers and iterate.",
        icon: "rocket",
      },
      {
        id: "scale",
        title: "6. Scale",
        description: "Scale operations, expand markets and compound value.",
        icon: "growth",
      },
    ],
    capabilityList: [],
    partners: [],
    technologies: [],
    cta: {
      eyebrow: "Build with Olympia",
      title: "See what the system has built.",
      description: "Explore our products and solutions.",
      buttonLabel: "Explore Products",
    },
    partnerOptions: [
      {
        id: "build-with-us",
        title: "Build with us",
        description: "Entrepreneurs and domain experts bring opportunities. We help you validate, build and scale.",
        icon: "users",
        accent: "green",
      },
      {
        id: "corporate-venture",
        title: "Corporate venture",
        description:
          "Organizations partner with Olympia to create new technology businesses in adjacent or new markets.",
        icon: "building",
        accent: "blue",
      },
      {
        id: "originated-venture",
        title: "ANTIKRA-originated venture",
        description: "Olympia identifies and develops opportunities internally and builds ventures from the ground up.",
        icon: "compass",
        accent: "bronze",
      },
    ],
    principles: [
      {
        id: "impact-first",
        title: "Impact first",
        description: "We build ventures that solve real problems and create lasting value.",
        icon: "heart",
      },
      {
        id: "long-term-thinking",
        title: "Long-term thinking",
        description: "We build for resilience, not just early traction.",
        icon: "shield",
      },
      {
        id: "customer-obsession",
        title: "Customer obsession",
        description: "We start with the user and never lose sight of them.",
        icon: "users",
      },
      {
        id: "operating-excellence",
        title: "Operating excellence",
        description: "Disciplined execution, data-driven decisions and continuous learning.",
        icon: "growth",
      },
      {
        id: "system-leverage",
        title: "System leverage",
        description: "We multiply outcomes by bringing the full power of the ANTIKRA system.",
        icon: "nodes",
      },
    ],
    finalCta: {
      title: "Six companies. One system.",
      description:
        "Olympia turns insight into companies. The ANTIKRA system turns those companies into enduring impact.",
      secondaryTitle: "See what the system has built.",
      secondaryDescription: "Explore our products and solutions.",
      buttonLabel: "Explore Products",
      href: "/products",
    },
  },
}
